baseURL = "/"
languageCode = "en-us"
title = "Umberto D'Ovidio"
theme = "beautifulhugo"
defaultContentLanguage = "en"

[Params]
  homeTitle = "Blog"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  mainSections = ["post","posts"]
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[languages]
  [languages.en]
    contentDir = "content/en" # English
    flagName = "gb" 
    LanguageName = "English"
  [languages.it] 
    contentDir = "content/it" # Italian
    flagName = "it"
    LanguageName = "Italiano"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1
[[menu.main]]
    name = "Now"
    url = "page/now/"
    weight = 3    
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3